name = "Eugene"
uuid = "68329af8-4b11-48ad-b396-d55763028886"
repo = "git@github.com:eugene-shvarts/EugeneRegistry.git"
description = "Julia registry for Eugene things"

[packages]
a5579899-0d95-4cd7-b984-e47de3a774e9 = { name = "Cadcad", path = "C/Cadcad" }
